### ISSUE TITLE
Setup-Kanbanboard

### ISSUE THREAD

**Issue by Haywayaheadshot** [Haywayaheadshot/book-an-appointment#13]
- Team members: 4 namely
  > @Kelvin-Ben 
  > @asnganje
  > @Haywayaheadshot
  > @eng-mohamed-eldeeb 

- [Link to Project](https://github.com/users/Haywayaheadshot/projects/10)

![2023-03-01_17h32_57](https://user-images.githubusercontent.com/105272189/222217623-b7531c57-e8d1-495d-994a-9db7dbe55aae.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Equitable distribution of tasks
- Good description of tasks
- Seem to have covered all core elements of project


## Optional suggestions
- Consider adding labels to your issues

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@mcrd25 Thank you for reviewing our project. Have a nice day
